app/urls.py
from django.urls import path, include
from .views import home, rental_service, catalogue, contact,\
    add_product, list_product, update_product, delete_product,\
    ProductViewset, CategoryViewset, register, product_detail,\
    add_prod_cart, del_prod_cart, subtract_product_cart,\
    clean_cart, cart_page, buy_confirm, add_category,\
    list_category, update_category, delete_category, admin_panel,\
    ContactViewSet,pago, list_contact,\
    QueryTypeViewset, update_contact_status, add_query_type, list_query_type,\
    update_query_type, delete_query_type, RentalOrderViewSet, list_rental_order


from unicodedata import name
from . import views
#from .views import index

from .views import Registrar, order_list
from django.contrib.auth.views import LoginView
from .views import Recuperar,login
from .views import user_login
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static



from .views import payment_success
from .views import obtain_token


from rest_framework import routers

router = routers.DefaultRouter()
router.register('product', ProductViewset)
router.register('category', CategoryViewset)
router.register('contact', ContactViewSet, basename='contact')
router.register('query-type', QueryTypeViewset, basename='query-type')
router.register(r'rental-orders', RentalOrderViewSet)


urlpatterns = [
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('', home, name="home"),
    path('catalogue/', catalogue, name="catalogue"),
    path('rental-service/', rental_service, name="rental_service"),
    path('contact/', contact, name="contact"),
    path('list-contact/', list_contact, name="list_contact"),
    path('update-status/<int:contact_id>/', update_contact_status, name='update_status'),
    path('add-query-type/', add_query_type, name="add_query_type"),
    path('list-query-type/', list_query_type, name="list_query_type"),
    path('update-query-type/<int:id>/', update_query_type, name="update_query_type"),
    path('delete-query-type/<id>/', delete_query_type, name="delete_query_type"),
    path('add-product/', add_product, name="add_product"),
    path('list-product/', list_product, name="list_product"),
    path('update-product/<int:id>/', update_product, name="update_product"),
    path('delete-product/<id>/', delete_product, name="delete_product"),
    path('product-detail/<int:id>/', product_detail, name="product_detail"),
    path('add-category/', add_category, name="add_category"),
    path('list-category/', list_category, name="list_category"),
    path('update-category/<id>/', update_category, name="update_category"),
    path('delete-category/<id>/', delete_category, name="delete_category"),
    path('api/', include(router.urls)),
    path("add/<int:product_id>", add_prod_cart, name="Add"),
    path("delete/<int:product_id>", del_prod_cart, name="Del"),
    path("subtract/<int:product_id>", subtract_product_cart, name="Sub"),
    path("clean/", clean_cart, name="Clean"),
    path("cart/", cart_page, name="Cart"),
    path("buy-confirm/", buy_confirm, name="buy_confirm"),
    path("admin-panel/", admin_panel, name="admin_panel"),
    path('pago/', pago, name="pago"),
    path('Recuperar/', Recuperar, name='Recuperar'),
    path('payment_success/', payment_success, name='payment_success'),
    path('payment_success/', views.update_last_order_paid_status, name='update_last_order_paid_status'),
    path('orders/', order_list, name='order_list'),
    path('list-rental-order/', list_rental_order, name="list_rental_order"),
    path('Registrar/', Registrar, name='Registrar'),   
    path('payment_success/', payment_success, name='payment_success'),
    path('payment_success/', views.update_last_order_paid_status, name='update_last_order_paid_status'),
    path('api/token/', views.obtain_token, name='obtain_token'),
    path('login/', user_login, name='login'),
    path('api/token/', obtain_token, name='obtain_token'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('api/login', login, name='login_api'),
]

conejofurioso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from conejofurioso.viewsLogin import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('login/', login, name='login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone



#categorias para producto
class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    image = models.ImageField(upload_to="categories/", blank=True, null=True)

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        sin_categoria, _ = Category.objects.get_or_create(name='Sin categoría', defaults={'description': 'Categoría predeterminada para productos sin categoría'})
        products = self.product_set.all()
        for product in products:
            product.category = sin_categoria
            product.save()
        super().delete(*args, **kwargs)

#producto
class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    description = models.TextField(max_length=200)
    is_new = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    stock = models.IntegerField()
    is_featured = models.BooleanField(default=False)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_rentable = models.BooleanField(default=False)

    def __str__(self):
        return self.name

#tipo de consulta
class QueryType(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.name

#consulta
class Contact(models.Model):
    STATUS_CHOICES = (
        ('Nuevo', 'Nuevo'),
        ('En progreso', 'En progreso'),
        ('Finalizado', 'Finalizado'),
    )

    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()
    message = models.TextField(max_length=200)
    query_type = models.ForeignKey(QueryType, on_delete=models.PROTECT)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Nuevo')

    def __str__(self):
        return self.name

class Usuarios(models.Model):
    usrN= models.CharField(max_length=100,verbose_name="Nombre de Usuario")
    pswrdN= models.CharField(max_length=15, verbose_name="Contraseña")
    pswrdN2=models.CharField(max_length=15, verbose_name="Contraseña2")
#fin modelos para usuarios

#se crea modelo de token
class Tokens(models.Model):
    token= models.CharField(max_length=256)
    user = models.CharField(max_length=256)    

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    order_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=20, null=True)
    accumulated = models.DecimalField(max_digits=10, decimal_places=2)
    pagado = models.BooleanField(null=True, default=False)
    fecha = models.DateField(default=timezone.now)  # Agregar el campo fecha con la fecha actual por defecto

    def __str__(self):
        return f"Order {self.order_id} - User: {self.user.username if self.user else 'None'}"
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=100)
    product_price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.IntegerField()

    def __str__(self):
        return f"{self.product_name} - Amount: {self.amount}"  
    
class RentalOrder(models.Model):
    rut = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    deliver_date = models.DateTimeField()
    products = models.ManyToManyField(Product)

    def __str__(self):
        return self.name

app/forms.py
from django import forms
from .models import Contact, Product, Category, QueryType, RentalOrder
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.contrib.auth.forms import UserCreationForm
from .validators import MaxSizeFileValidator
from django.forms import ValidationError
from django.core.validators import validate_email, MinValueValidator
from django.core.exceptions import ValidationError
from django.contrib.admin.widgets import AdminDateWidget


from dataclasses import fields
from django import forms
from django.forms import ModelForm
from .models import  Usuarios
from allauth.account.forms import LoginForm


class ContactForm(forms.ModelForm):
    name = forms.CharField(min_length=8, max_length=50,
                           required=True, label='Nombre completo')
    email = forms.EmailField(required=True, label='Correo electrónico')
    phone = forms.IntegerField(
        label='Teléfono', min_value=100000000, max_value=999999999)
    message = forms.CharField(required=True, max_length=200, label='Mensaje', widget=forms.Textarea)
    query_type = forms.ModelChoiceField(
        queryset=QueryType.objects.all(), required=True, label='Tipo de consulta')

    class Meta:
        model = Contact
        fields = ["name", "email", "phone", "message", "query_type"]
        labels = {
            'name': 'Nombre completo',
            'email': 'Correo electrónico',
            'phone': 'Teléfono',
            'message': 'Mensaje',
            'query_type': 'Tipo de consulta'
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            validate_email(email)
        except ValidationError:
            raise forms.ValidationError(
                "El correo electrónico no es válido.")
        return email

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(str(phone)) != 9:
            raise forms.ValidationError(
                "El número de teléfono debe contener 9 dígitos.")
        return phone

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        queryType = cleaned_data.get('queryType')
        name = cleaned_data.get('name')
        phone = cleaned_data.get('phone')

        if not email:
            self.add_error('email', 'Este campo es obligatorio.')
        if not queryType:
            self.add_error('queryType', 'Este campo es obligatorio.')
        if name and len(name) < 8:
            self.add_error(
                'name', 'El nombre debe tener al menos 8 caracteres.')
        if phone:
            try:
                cleaned_phone = self.clean_phone()
                cleaned_data['phone'] = cleaned_phone
            except forms.ValidationError as e:
                self.add_error('phone', e.message)

class QueryTypeForm(forms.ModelForm):
    name = forms.CharField(min_length=3, max_length=50)


    class Meta:
        model = QueryType
        fields = '__all__'
        labels = {
            'name': 'Nombre',
            'description': 'Descripcion',
        }

class ProductForm(forms.ModelForm):
    image = forms.ImageField(required=False, validators=[MaxSizeFileValidator(20)])
    name = forms.CharField(min_length=3, max_length=50)
    price = forms.IntegerField(min_value=1, max_value=1500000)
    stock = forms.IntegerField(validators=[MinValueValidator(0)])
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True)


    class Meta:
        model = Product
        fields = '__all__'
        labels = {
            'name': 'Nombre',
            'description': 'Descripción',
            'price': 'Precio',
            'category': 'Categoría',
            'stock': 'Unidades',
            'is_new': '¿Nuevo?',
            'is_featured': '¿Destacado?',
            'image': 'Imagen',
            'is_rentable': '¿Arrendable?'
        }

class CustomUserCreationForm(UserCreationForm):
    pass

class CategoryForm(forms.ModelForm):

    image = forms.ImageField(required=False, validators=[
                             MaxSizeFileValidator(20)])
    name = forms.CharField(min_length=3, max_length=50)


    class Meta:
        model = Category
        fields = '__all__'
        labels = {
            'name': 'Nombre',
            'description': 'Descripcion',
            'image': 'Imagen'
        }

class UsuariosForm(ModelForm):
    #se da formato a cada uno de los campos dentro de la forma
    usrN = forms.CharField(widget=forms.EmailInput(attrs={'class':'login-username','placeholder':'Email'}),label='')
    pswrdN = forms.CharField(widget=forms.PasswordInput(attrs={'class':'login-password','placeholder':'Contraseña'}),label='')
    pswrdN2= forms.CharField(widget=forms.PasswordInput(attrs={'class':'login-password','placeholder':'Repetir Contraseña'}),label='')
    class Meta:
        #se asigna modelo y orden de aparicion en html
        model = Usuarios
        fields= ['usrN','pswrdN','pswrdN2']

class LoginForm(ModelForm):
    usrN = forms.CharField(widget=forms.TextInput(attrs={'class':'login-username','placeholder':'Username'}),label='')
    pswrdN = forms.CharField(widget=forms.PasswordInput(attrs={'class':'login-password','placeholder':'Contraseña'}),label='')
    class Meta:
        model=Usuarios
        fields= ['usrN','pswrdN']
        
class RentalOrderForm(forms.ModelForm):
    name = forms.CharField(min_length=3, max_length=50)


    class Meta:
        model = RentalOrder
        fields = '__all__'
        labels = {
            'rut': 'Rut',
            'name': 'Nombre',
            'address': 'Direccion',
            'phone': 'Celular',
            'deliver_date': 'Fecha de entrega'
        }

class RecuperarForm(forms.Form):
    email = forms.EmailField(label='Correo electrónico')

app/templates/app/cart.html
<div class="container">
<div class="alert alert-secondary my-5" role="alert">
    <table class="table table-bordered table-hover table-responsive-sm">
        <thead>
            <tr>
                <h2 style="text-align: center; justify-content: center;" class="my-2">Carrito</h1>
                    <br>
            </tr>
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% if request.session.cart.items %}
            {% for key, value in request.session.cart.items %}
            <tr>
                <td><strong>{{value.product_name}}</strong></td>
                <td>{{value.product_price}}</td>
                <td>{{value.amount}}
                    <a href="{% url 'Add' value.product_id %}" class="badge btn btn-dark badge-dark">+</a>
                    <a href="{% url 'Sub' value.product_id %}" class="badge btn btn-dark badge-dark">-</a>
                </td>
                <td>{{value.accumulated}}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">
                    <div class="alert alert-danger text-center">Sin Productos</div>
                </td>
            </tr>
            {% endif %}
                <tr>
                    <th colspan="3" class="text-right">Total Compra:</th>
                    <th>$ {{cart_total}}</th>
                </tr>
        </tbody>
    </table>
    <hr>
    <div class="row text-center">
        <div class="col-6">
            <a href="{% url 'Clean' %}" class="btn btn-danger">Limpiar</a>
        </div>
        <div class="col-6">
            {% if request.session.cart.items %}
            <a href="{% url 'pago' %}" class="btn btn-warning">Pagar</a>
            {% else %}
            <button class="btn btn-warning" disabled>Pagar</button>
            {% endif %}
            <a href="{% url 'catalogue' %}" class="btn btn-primary">Seguir comprando</a>
        </div>
    </div>
</div>

app/templates/app/cart_page.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<title>Conejo Furioso</title>
{% endblock %}

{% block content %}
<br><br><br><br>
<div id="cart-container">
    <main class="container">
        {% include "app/cart.html" %}
        {% if request.session.cart.items %}
        <div class="row text-center">
            {% comment %}
            <div class="col-6"><a href="{% url 'Clean' %}" class="btn btn-default bg-primary-3">Limpiar</a></div>

            <div class="col-6"><a href="{% url 'Checkout' %}" class="btn btn-default bg-primary-3 add-to-cart-btn">Ir al pago</a></div>
            {% endcomment %}
        </div>
        {% else %}
        {% endif %}
    </main>
</div>
{% endblock %}

app/templates/app/order_list.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
{% load humanize %}

<br><br><br>
<div class="container my-5">
    <br><br>
    <div class="card">
        <div class="card-body">
            <center>
                <h2>Lista de Ordenes</h2>
            </center>
            <hr>
            <div class="table-responsive">
                <!-- Formulario de filtros -->
                <form method="GET" action="{% url 'order_list' %}">
                    <div class="row mt-1 mb-3">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="start_date">Fecha inicial:</label>
                                <input type="date" id="start_date" name="start_date" class="form-control"
                                    value="{{ request.GET.start_date }}">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="end_date">Fecha final:</label>
                                <input type="date" id="end_date" name="end_date" class="form-control"
                                    value="{{ request.GET.end_date }}">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="order_item_name">Nombre de OrderItem:</label>
                                <input type="text" id="order_item_name" name="order_item_name" class="form-control"
                                    value="{{ request.GET.order_item_name }}">
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="form-group">
                                <label>&nbsp;</label>
                                <button class="btn btn-default bg-primary-3 form-control" type="submit">Filtrar</button>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>&nbsp;</label>
                                <a href="{% url 'order_list' %}" class="btn btn-default bg-primary-3 add-to-cart-btn form-control">Limpiar
                                    filtros</a>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- Fin del formulario de filtros -->

                <table id="productTable" class="table table-striped table-hover table-responsive-sm">
                    <thead>
                        <tr>
                            <th>Usuario</th>
                            <th>Numero de orden</th>
                            <th>Nombre</th>
                            <th>Direccion</th>
                            <th>Celular</th>
                            <th>Acumulado</th>
                            <th>Pagado</th>
                            <th>Fecha</th>
                            <th>Order Items</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for o in entity %}
                        <tr>
                            {% if o.user.username %}
                            <td>{{ o.user.username }}</td>
                            {% else %}
                            <td>N/A</td>
                            {% endif %}

                            <td>{{ o.order_id }}</td>

                            {% if o.name %}
                            <td>{{ o.name }}</td>
                            {% else %}
                            <td>N/A</td>
                            {% endif %}

                            {% if o.address %}
                            <td>{{ o.address }}</td>
                            {% else %}
                            <td>N/A</td>
                            {% endif %}

                            {% if o.phone %}
                            <td>{{ o.phone }}</td>
                            {% else %}
                            <td>N/A</td>
                            {% endif %}

                            <td>{{ o.accumulated | intcomma }}</td>

                            {% if o.pagado %}
                            <td>Si</td>
                            {% else %}
                            <td>No</td>
                            {% endif %}

                            <td>{{ o.fecha }}</td>

                            <td>
                                <ul>
                                    {% for item in o.orderitem_set.all %}
                                    <li>{{ item.product_name }} - Cantidad: {{ item.amount }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="total-accumulated">
                    <h4>Total acumulado de todas las órdenes: $ {{ total_accumulated }}</h4>
                    <h4>Total de productos vendidos: {{ total_products_sold }}</h4>
                </div>

                <div class="top-products">
                    <h3>Productos más vendidos:</h3>
                    <ul>
                        {% for product in top_products %}
                        <li>{{ product.product_name }} - Cantidad vendida: {{ product.total_amount }}</li>
                        {% endfor %}
                    </ul>
                </div>

                <hr>
                <div>
                    {% include 'app/paginator.html' %}
                </div>
            </div>

            <br>
            <div class="row list-buttons">
                <div class="col">
                    <a href="{% url 'home' %}">
                        <button class="btn btn-default bg-primary-3" type="button">Volver al Inicio</button>
                    </a>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="{% static 'core/js/jquery-3.6.0.js'%}"></script>

{% endblock %}

app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center pagination-container">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

app/templates/app/pago.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<title>Conejo Furioso</title>
<style>
    .cart-table {
      border: 12px solid hwb(6 6% 16%);
    }
  </style>
{% endblock %}

{% block content %}
<div class="container">
<style>
    .cart-table {
      border: 12px solid hwb(90 58% 9%);
    }
  </style>
<div class="alert alert-secondary my-5" role="alert"></div>
<table class="table table-bordered table-hover table-responsive-sm cart-table">
   
    <thead>
        <tr>
            <h2 style="text-align: center; justify-content: center;" class="my-2">Información de Pago</h1>
                <br>
        </tr>
        <tr>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.cart.items %}
        {% for key, value in request.session.cart.items %}
        <tr>
            <td><strong>{{ value.product_name }}</strong></td>
            <td>{{ value.product_price }}</td>
            <td>{{ value.amount }}</td>
            <td>{{ value.accumulated }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">
                <div class="alert alert-danger text-center">Sin Productos</div>
            </td>
        </tr>
        {% endif %}
        <tr>
            <th colspan="3" class="text-right">Total Compra (CLP):</th>
            <th id="cart-total-clp">{{ cart_total }}</th>
        </tr>
        <tr>
            <th colspan="3" class="text-right">Total Compra (USD):</th>
            <th id="cart-total">{{ cart_total }}</th>
        </tr>
    </tbody>
</table>
</div>
<br><br>
<div class="container">
    <div class="row">
        <div class="col">
            <h2>Datos del comprador</h2>

            <form method="POST" action="{% url 'payment_success' %}">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="id_user" class="col-sm-2 col-form-label">Usuario</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="id_user" name="user" value="{{ user.username }}" readonly>
                    </div>
                </div>
                {% for key, value in request.session.cart.items %}
                <div class="form-group row">
                    <label for="product_{{ key }}" class="col-sm-2 col-form-label">Producto</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="product_{{ key }}" name="product_{{ key }}" value="{{ value.product_name }} - Cantidad: {{ value.amount }}" readonly>
                    </div>
                </div>
                {% endfor %}

                
                <div class="form-group row">
                    <label for="id_name" class="col-sm-2 col-form-label">Nombre</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="id_name" name="name">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_adress" class="col-sm-2 col-form-label">Dirección</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="address" name="address">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_telefono" class="col-sm-2 col-form-label">Teléfono</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="phone" name="phone">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_total_clp" class="col-sm-2 col-form-label">Total CLP</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="accumulated" name="accumulated" value="{{ cart_total }}" readonly>
                    </div>
                </div>

                <button type="submit" class="btn btn-success btn-product">
                    <span class="glyphicon glyphicon-shopping-cart"> Continuar con el pago</span> 
                </button>
            </form>
        </div>
    </div>
</div>
</div>
          
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
 // Función para actualizar el estado de pago de la última orden en Django
function updateLastOrderPaidStatus(user) {
// Realizar una redirección a la URL correspondiente en Django para actualizar el estado de pago
 window.location.href = "/update_last_order_paid_status/";
            }
// Función para convertir el total de CLP a dólares
function convertToUSD(totalCLP) {
// Tasa de conversión: 1 CLP = 0.0014 USD (valor de ejemplo)
var conversionRate = 0.00124;
var totalUSD = totalCLP * conversionRate;
return totalUSD.toFixed(2);
}

// Obtener el total en CLP desde la variable de contexto
var totalCLP = parseInt("{{ cart_total }}");

// Calcular el total en USD llamando a la función de conversión
var totalUSD = convertToUSD(totalCLP);

// Mostrar los totales en la página
document.getElementById("cart-total-clp").textContent = totalCLP;
document.getElementById("cart-total").textContent = totalUSD;
</script>

</html>
{% endblock %}